jackson:
  bean-introspection-module: true
datasources:
  default:
    url: ${DB_URL}
    driverClassName: ${DB_DRIVERCLASSNAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schema-generate: CREATE_DROP
    dialect: POSTGRES
endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
micronaut:
  application:
    name: customer-service
  router:
    static-resources:
      swagger-ui:
        paths: classpath:META-INF/swagger-ui
        mapping: /swagger-ui/**
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**


