jackson:
  bean-introspection-module: true
datasources:
  default:
    url: ${DB_URL}
    driverClassName: ${DB_DRIVERCLASSNAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schema-generate: CREATE_DROP
    dialect: POSTGRES
    maxActive: 2
    maxIdle: 2
    minIdle: 0
    initialSize: 2
jpa:
  default:
    packages-to-scan:
      - 'io.eventuate.examples.tram.ordersandcustomers.orders.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
micronaut:
  application:
    name: order-service
  router:
    static-resources:
      swagger-ui:
        paths: classpath:META-INF/swagger-ui
        mapping: /swagger-ui/**
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
